name: ${plugin.name}
main: ${plugin.mainClass}
version: ${project.version}
description: ${plugin.description}
commands:
  configedit:
    description: Edits the config in the specified plugin's directory.
    usage: /<command> <plugin|:folder-path> <key:value> [file]
    permission: ${plugin.name}.command
    aliases: [edit, ce]
